### ISSUE TITLE
Ubuntu 22.04 LTS 环境上，gevent依赖包版本存在差异

### ISSUE THREAD

**Issue by ruishawn** [spmonkey/GHR#3]
Ubuntu 22.04 LTS 环境上，`pip3 install -r requirements.txt` gevent依赖包报错，可能是pip源的差异造成的，可以通过修改版本避免问题产生

![image](https://github.com/spmonkey/GHR/assets/5628817/165af984-044e-42b4-8009-d24864667c92)

**Comment by spmonkey** [comment]
好的，感谢反馈
